In [35]:
import pandas as pd

df = pd.read_excel("../data/FMIS_lokalen.xlsx",header=1)
df

,PK_fmis_lokalen,Code,Campus,Gebouw,Verdieping,Lokaal,Site-beschrijving,Gebouw-beschrijving,Verdieping-beschrijving,Lokaal-ID,Lokaal-Beschrijving,Categorie,Oppervlakte,Locatie-ID,Code2,TimeEdit,Van,Tot,Capaciteit
0,1,26.01.140.024,26.0,1.0,140.0,24,26 - Campus Vesalius,26.01 - GVESA,26.01 - GVESA140,24,GVESA.4.studentenkamer,studentenkamer,0.00,23180.0,GVESA.4.stu,0.0,2020-10-01 00:00:00.000,NaN,NaN
1,2,26.01.120.023,26.0,1.0,120.0,23,26 - Campus Vesalius,26.01 - GVESA,26.01 - GVESA120,23,GVESA.2.studentenkamer,studentenkamer,11.11,22882.0,GVESA.2.stu,0.0,2020-10-01 00:00:00.000,NaN,NaN
2,3,26.01.150.075,26.0,1.0,150.0,75,26 - Campus Vesalius,26.01 - GVESA,26.01 - GVESA150,75,GVESA.5.studentenkamer,studentenkamer,0.00,23424.0,GVESA.5.stu,0.0,2020-10-01 00:00:00.000,NaN,NaN
3,4,26.01.170.006,26.0,1.0,170.0,6,26 - Campus Vesalius,26.01 - GVESA,26.01 - GVESA170,6,GVESA.7.studentenkamer,studentenkamer,0.00,23588.0,GVESA.7.stu,0.0,2020-10-01 00:00:00.000,NaN,NaN
4,5,26.01.150.014,26.0,1.0,150.0,14,26 - Campus Vesalius,26.01 - GVESA,26.01 - GVESA150,14,GVESA.5.studentenkamer,studentenkamer,0.00,23308.0,GVESA.5.stu,0.0,2020-10-01 00:00:00.000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7068,7069,01.03.100.028,1.0,3.0,100.0,28,01 - Campus Schoonmeersen,01.03 - GSCHC,01.03 - GSCHC100,28,GSCHC.0.028 Ongedefinieerd,vergaderzaal,0.00,35604.0,NaN,0.0,2020-10-01 00:00:00.000,2024-11-21 00:00:00.000,NaN
7069,7070,01.03.100.066,1.0,3.0,100.0,66,01 - Campus Schoonmeersen,01.03 - GSCHC,01.03 - GSCHC100,66,GSCHC.0.066 Gaskot,opslagplaats,17.58,11367.0,NaN,0.0,2020-10-01 00:00:00.000,2024-11-21 00:00:00.000,NaN
7070,7071,01.03.100.065,1.0,3.0,100.0,65,01 - Campus Schoonmeersen,01.03 - GSCHC,01.03 - GSCHC100,65,GSCHC.0.065 Gaskot,opslagplaats,17.58,11365.0,NaN,0.0,2020-10-01 00:00:00.000,2024-11-21 00:00:00.000,NaN
7071,7072,01.03.100.070,1.0,3.0,100.0,70,01 - Campus Schoonmeersen,01.03 - GSCHC,01.03 - GSCHC100,70,GSCHC.0.070 Verbindingsgang + lockers,gang,131.62,11417.0,NaN,0.0,2020-10-01 00:00:00.000,2024-11-21 00:00:00.000,NaN
7072,7073,01.03.140.133,1.0,3.0,140.0,133,01 - Campus Schoonmeersen,01.03 - GSCHC,01.03 - GSCHC140,133,GSCHC.4.133 Berging + technische ruimte,berging,24.22,11907.0,NaN,0.0,2020-10-01 00:00:00.000,2024-11-21 00:00:00.000,NaN

In [36]:
gschb_df = df[df['Gebouw-beschrijving'].str.contains("GSCHB", na=False)]
gschb_df

,PK_fmis_lokalen,Code,Campus,Gebouw,Verdieping,Lokaal,Site-beschrijving,Gebouw-beschrijving,Verdieping-beschrijving,Lokaal-ID,Lokaal-Beschrijving,Categorie,Oppervlakte,Locatie-ID,Code2,TimeEdit,Van,Tot,Capaciteit
360,361,01.02.110.048,1.0,2.0,110.0,48,01 - Campus Schoonmeersen,01.02 - GSCHB,01.02 - GSCHB110,48,GSCHB.1.009a,NaN,NaN,NaN,NaN,NaN,2019-01-01 00:00:00.000,2020-10-01 00:00:00.000,NaN
365,366,01.02.110.049,1.0,2.0,110.0,49,01 - Campus Schoonmeersen,01.02 - GSCHB,01.02 - GSCHB110,49,GSCHB.1.009b,NaN,NaN,NaN,NaN,NaN,2019-01-01 00:00:00.000,2020-10-01 00:00:00.000,NaN
411,412,01.02.130.040,1.0,2.0,130.0,40,01 - Campus Schoonmeersen,01.02 - GSCHB,01.02 - GSCHB130,40,GSCHB.3.003,NaN,NaN,NaN,NaN,NaN,2019-01-01 00:00:00.000,2020-10-01 00:00:00.000,NaN
414,415,01.02.120.044,1.0,2.0,120.0,44,01 - Campus Schoonmeersen,01.02 - GSCHB,01.02 - GSCHB120,44,GSCHB.2.017,NaN,NaN,NaN,NaN,NaN,2019-01-01 00:00:00.000,2020-10-01 00:00:00.000,NaN
432,433,01.02.100.034,1.0,2.0,100.0,34,01 - Campus Schoonmeersen,01.02 - GSCHB,01.02 - GSCHB100,34,GSCHB.0.034 Consultatieruimte,consultatie,12.00,34377.0,GSCHB.0.034,1.0,2020-10-01 00:00:00.000,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3101,3102,01.02.100.016,1.0,2.0,100.0,16,01 - Campus Schoonmeersen,01.02 - GSCHB,01.02 - GSCHB100,16,GSCHB.0.016,burelen,37.46,25091.0,GSCHB.0.016,0.0,2020-10-01 00:00:00.000,NaN,NaN
3105,3106,01.02.120.032,1.0,2.0,120.0,32,01 - Campus Schoonmeersen,01.02 - GSCHB,01.02 - GSCHB120,32,GSCHB.2.032,burelen,17.39,10999.0,GSCHB.2.032,0.0,2020-10-01 00:00:00.000,NaN,NaN
3110,3111,01.02.120.029,1.0,2.0,120.0,29,01 - Campus Schoonmeersen,01.02 - GSCHB,01.02 - GSCHB120,29,GSCHB.2.029,burelen,34.66,11077.0,GSCHB.2.029,0.0,2020-10-01 00:00:00.000,NaN,NaN
3115,3116,01.02.110.041,1.0,2.0,110.0,41,01 - Campus Schoonmeersen,01.02 - GSCHB,01.02 - GSCHB110,41,GSCHB.1.041,burelen,49.72,10913.0,GSCHB.1.041,0.0,2020-10-01 00:00:00.000,NaN,NaN
3116,3117,01.02.100.015,1.0,2.0,100.0,15,01 - Campus Schoonmeersen,01.02 - GSCHB,01.02 - GSCHB100,15,GSCHB.0.015,burelen,37.66,25089.0,GSCHB.0.015,0.0,2020-10-01 00:00:00.000,NaN,NaN

In [37]:
gschb_df["Categorie"].value_counts()

Categorie
leslokaal               30
laptoplokaal            28
burelen                 24
sanitair                22
berging                 22
gang                    16
vergaderzaal            10
technische ruimte       10
auditorium               9
sas                      9
samenvoeging lokalen     6
instrumentenlokaal       6
ongedefinieerd           4
PC-klas                  4
technieken               4
dienstkeuken             4
evenementenruimte        3
consultatie              3
laboratorium             3
practicum                2
Grasperk (vbMVE)         2
kleedkamer               2
ICT                      2
HVAC                     2
magazijn                 2
receptie/onthaal         1
liftkokers               1
inkom                    1
PR-lokaal                1
landschapsburelen        1
restaurant               1
atelier                  1
liftmachine              1
traphal                  1
docentenruimte           1
fotokopieerlokaal        1
Name: count, dtype: int64

In [38]:
# Unieke GSCHB lokalen opslaan in csv bestand
unique_rooms = gschb_df["Lokaal-Beschrijving"].unique()
unique_df = pd.DataFrame(unique_rooms, columns=["Lokaal-Beschrijving"])
unique_df

               Lokaal-Beschrijving
0                     GSCHB.1.009a
1                     GSCHB.1.009b
2                      GSCHB.3.003
3                      GSCHB.2.017
4    GSCHB.0.034 Consultatieruimte
..                             ...
241                    GSCHB.0.016
242                    GSCHB.2.032
243                    GSCHB.2.029
244                    GSCHB.1.041
245                    GSCHB.0.015

[246 rows x 1 columns]

In [39]:
unique_df.to_csv("../data/unique_gschb_rooms.csv", index=False)